# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];
  boot.kernelParams = [''acpi_osi="!Windows 2020"''];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/3157c771-9d91-4617-b8ba-6168dfe998fe";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-eff4e298-a9f3-4027-a03e-1c21b104287d".device = "/dev/disk/by-uuid/eff4e298-a9f3-4027-a03e-1c21b104287d";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FDA8-2383";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/092da54c-bd55-4d6e-9b6e-0bad1ed58662";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
