# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
    initrd = {
      availableKernelModules = ["xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
      kernelModules = [];
    };
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/335a261f-ad46-42d6-a209-ba449d6d4f0b";
    fsType = "ext4";
  };

  fileSystems."/home/luuk/media" = {
    # device = "/dev/disk/by-uuid/A1eCjH-xJ49-RfXD-endL-lgs5-7XbO-VAILdA";
    device = "/dev/mapper/vg--data-media";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0C0D-45C3";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/0842ae0d-26fc-44d1-a4f7-cbabae291152";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
